My first commit
YannickZahinda/My-Portfolio-design pull request #1
Opened 2022-02-16 13:23 UTC by YannickZahinda

>Title: My first portfolio 

In this project I performed a mobile version skeleton of my first portfolio, the requirements were  :

>>General requirements

Make sure that there are [no linter errors](https://github.com/microverseinc/linters-config):
Linter should be set up correctly for this repository.
Linter result should be green.
There should be no custom changes to linter config.
Make sure that you used correct [GitHub Flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md):
README file should be descriptive.
Commit messages should be meaningful.
Pull Request should have a descriptive title explaining what changes are inside.
Pull Request should have a short summary describing introduced changes in more detail.
Make sure that you documented your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md):
Branch name should describe a feature or action (e.g. 'created_sidebar' or 'added_comments_section').
Pull Request is made from 'feature branch' into the main branch.

2022-02-16 14:13 UTC, Donard97 requested changes
## Hi @YannickZahinda , 👋  

You did tremendous work so far but you have a few more steps! 👏 💯

There are some issues that you still need to work on to go to the next project but you are almost there! 👍 

![giphy (5)](https://user-images.githubusercontent.com/74506933/154282352-eb5c9052-0976-476b-93ab-414e5f950ad5.gif)

## Required Changes ♻️

- [ ] Kindly add .gitignore file and ignore node_modules and .DS_Store
- [ ] Please try to do more commits in the future and try to give a more meaningful name of the commits that you are doing
- [ ] Kindly change the title of PR and do it more descriptive. You have to tell us what you did in this branch.
- [ ] Please check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-02-16 14:13 UTC, Donard97 commented on index.html
> +        </ul>
- [ ] Good job on adding social media icons but kindly add them inside of the second section and wrap icons inside of tag a because they are links that will redirect to your social media accounts. 👍 💪

2022-02-16 14:13 UTC, Donard97 commented on style.css
> +  margin-bottom: 15px;
- [ ] You did an amazing job designing your portfolio but I suggest you stick as much as you can to [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=48%3A2346). You have to add more padding and spacing following the design.

Here you have a screenshot of your project:

![image](https://user-images.githubusercontent.com/74506933/154281039-f7443be0-9578-4680-9cca-9a3d2fd2f514.png)

Here you have a screenshot of the Figma design:

![image](https://user-images.githubusercontent.com/74506933/154281152-e914100b-08c8-4874-835c-13c96860f437.png)

2022-02-16 14:13 UTC, Donard97 commented on README.md
> +### Deployment
- [ ] Good job on adding other details of the README file but please delete them if you don't have any information for them and for deployment if you want to leave it there and you don't have a live link you can mention that you are working on it. Keep coding 💪

2022-02-17 10:31 UTC, ReshyResh approved these changes
# Hi @YannickZahinda , 

### Good job addressing the changes requested by the previous reviewer.
#### Your project is complete!  There is nothing else to say other than... it's time to merge it!
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

----

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2022-02-17 10:49 UTC, merged